name: hellocsnap # you probably want to 'snapcraft register <name>'
version: '2.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Hello World snap written in C # 79 char long summary
description: This snap says hello and adds 2 numbers. 
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
apps:
 hello:
   command: hellocsnap
parts:
  vbota-hellocsnap:
    # See 'snapcraft plugins'
    plugin: autotools
    source: source/
